### Send POST request with json body
POST http://localhost:8080/parcel
Content-Type: application/json

{
  "weight": 10,
  "recipient": {
    "name": "Basem",
    "street": "Skraupstraße 24/18/22",
    "postalCode": "A-1210",
    "city": "Vienna",
    "country": "Austria"
  },
  "sender": {
    "name": "Ahmed",
    "street": "Am Schöpwerk 21",
    "postalCode": "A-1120",
    "city": "Vienna",
    "country": "Austria"
  }
}
###
