name: CD
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Download JAR
      uses: actions/download-artifact@v2
      with:
          name: artifact
          
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: parceltnt
        environment_name: Parceltnt-env
        version_label: 12345
        region: us-east-1
        deployment_package: openapi-spring-1.22.1
